"use client"
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Shield,Loader2,KeyRound,UserPlus}from"lucide-react";import{useAuth}from"@/context/auth-context";import{API_BASE_URL}from"@/lib/api";import{QRCodeSVG}from"qrcode.react"
export default function Login(){const router=useRouter();const{login,verifyTotp,verifyTotpSetup}=useAuth();const[email,setEmail]=useState("");const[pw,setPw]=useState("");const[code,setCode]=useState("");const[step,setStep]=useState<"login"|"totp"|"setup">("login");const[challenge,setChallenge]=useState("");const[setupToken,setSetupToken]=useState("");const[uri,setUri]=useState("");const[secret,setSecret]=useState("");const[recovery,setRecovery]=useState<string[]>([]);const[showRegister,setShowRegister]=useState(false);const[showForgot,setShowForgot]=useState(false);const[recoveryCode,setRecoveryCode]=useState("");const[newPassword,setNewPassword]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false)
useEffect(()=>{if(step==="setup"&&setupToken){fetch(API_BASE_URL+"/auth/totp/setup",{method:"POST",headers:{Authorization:"Bearer "+setupToken}}).then(x=>x.json()).then(x=>{setUri(x.otpauth_uri||"");setSecret(x.secret||"")}).catch(()=>setErr("Unable to start authenticator setup"))}},[step,setupToken])
const submit=async(e:React.FormEvent)=>{e.preventDefault();setErr("");setBusy(true);try{const x=await login(email,pw);if(x.type==="complete")router.push("/dashboard");else if(x.type==="totp"){setChallenge(x.challenge||"");setStep("totp")}else{setSetupToken(x.setupToken||"");setStep("setup")}}catch(x){setErr(x instanceof Error?x.message:"Login failed")}finally{setBusy(false)}}
const verify=async()=>{setErr("");setBusy(true);try{if(step==="setup")setRecovery(await verifyTotpSetup(setupToken,code));else{await verifyTotp(challenge,code);router.push("/dashboard")}}catch(x){setErr(x instanceof Error?x.message:"Verification failed")}finally{setBusy(false)}}
if(recovery.length)return <main className="app-shell flex min-h-screen items-center justify-center p-6"><section className="glass-panel w-full max-w-lg rounded-[2rem] p-8"><h1 className="text-3xl font-semibold">Save your recovery codes</h1><p className="mt-3 text-sm text-muted-foreground">Each code works once if you lose access to Google Authenticator.</p><div className="mt-6 grid gap-2 rounded-2xl border border-white/10 p-5">{recovery.map(x=><code key={x}>{x}</code>)}</div><Button className="mt-6 w-full" onClick={()=>router.push("/dashboard")}>Continue</Button></section></main>
if(step!=="login")return <main className="app-shell flex min-h-screen items-center justify-center p-6"><section className="glass-panel w-full max-w-lg rounded-[2rem] p-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Shield/></div><h1 className="mt-6 text-3xl font-semibold">{step==="setup"?"Set up Google Authenticator":"Enter authenticator code"}</h1>{step==="setup"&&uri&&<div className="mt-6 flex flex-col items-center gap-4"><div className="rounded-2xl bg-white p-4"><QRCodeSVG value={uri} size={220}/></div><code className="break-all text-xs">{secret}</code></div>}<Input className="mt-6 h-12 text-center text-xl tracking-[.4em]" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000"/>{err&&<p className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{err}</p>}<Button className="mt-4 w-full" disabled={busy||code.length!==6} onClick={verify}>{busy?<Loader2 className="animate-spin"/>:"Verify code"}</Button></section></main>
return <main className="app-shell flex min-h-screen items-center justify-center p-6"><section className="glass-panel w-full max-w-md rounded-[2rem] p-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Shield/></div><h1 className="mt-6 text-3xl font-semibold">RiskSure</h1><p className="mt-2 text-sm text-muted-foreground">Secure insurance intelligence platform</p><form onSubmit={submit} className="mt-8 space-y-5"><div><Label>Email</Label><Input className="mt-2 h-12" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div><Label>Password</Label><Input className="mt-2 h-12" type="password" value={pw} onChange={e=>setPw(e.target.value)} required/></div>{err&&<p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{err}</p>}<Button className="h-12 w-full" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:"Sign in"}</Button></form>
<div className="mt-5 flex justify-between text-sm">
<button type="button" className="text-primary hover:underline" onClick={()=>{setErr("");setShowRegister(true);setShowForgot(false)}}><UserPlus className="mr-1 inline h-4 w-4"/>Create account</button>
<button type="button" className="text-primary hover:underline" onClick={()=>{setErr("");setShowForgot(true);setShowRegister(false)}}><KeyRound className="mr-1 inline h-4 w-4"/>Forgot password?</button>
</div>
{showRegister&&<div className="mt-5 rounded-2xl border border-white/10 p-4"><p className="mb-3 font-medium">Create customer account</p><Input className="mb-3 h-11" type="password" placeholder="New password (8+ characters)" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><Button className="w-full" disabled={busy||newPassword.length<8} onClick={async()=>{setBusy(true);setErr("");try{const r=await fetch(API_BASE_URL+"/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password:newPassword,role:"customer"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Registration failed");setShowRegister(false);setErr("Account created. Sign in with your new password.")}catch(e){setErr(e instanceof Error?e.message:"Registration failed")}finally{setBusy(false)}}}>Register</Button></div>}
{showForgot&&<div className="mt-5 rounded-2xl border border-white/10 p-4"><p className="mb-2 font-medium">Reset password with a recovery code</p><p className="mb-3 text-xs text-muted-foreground">Use one of the recovery codes saved when authenticator setup was completed.</p><Input className="mb-3 h-11" placeholder="Recovery code" value={recoveryCode} onChange={e=>setRecoveryCode(e.target.value)}/><Input className="mb-3 h-11" type="password" placeholder="New password (8+ characters)" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><Button className="w-full" disabled={busy||!recoveryCode||newPassword.length<8} onClick={async()=>{setBusy(true);setErr("");try{const r=await fetch(API_BASE_URL+"/auth/password/reset-with-recovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,recovery_code:recoveryCode,new_password:newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Password reset failed");setShowForgot(false);setErr("Password reset successfully. You can sign in now.")}catch(e){setErr(e instanceof Error?e.message:"Password reset failed")}finally{setBusy(false)}}}>Reset password</Button></div>}
</section></main>}
