"use client"
import {useEffect,useState} from "react"
import {DashboardLayout} from "@/components/layout/dashboard-layout"
import {KPICard} from "@/components/dashboard/kpi-card"
import {StatusBadge} from "@/components/ui/status-badge"
import {Button} from "@/components/ui/button"
import {apiFetch,API_ENDPOINTS} from "@/lib/api"
import {FileText,CheckCircle,AlertTriangle,Plus,Loader2} from "lucide-react"
import Link from "next/link"
type Application={id:number;name:string;risk_score:number;decision:string;premium:number}
export default function DashboardPage(){const[a,setA]=useState<Application[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("")
useEffect(()=>{apiFetch(API_ENDPOINTS.applications).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load applications");setA(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
const approved=a.filter(x=>x.decision==="Approved").length,manual=a.filter(x=>x.decision==="Manual Review").length
return <DashboardLayout title="Dashboard" subtitle="Live RiskSure application overview"><div className="flex flex-col gap-6"><div className="grid gap-6 md:grid-cols-3"><KPICard title="Total Applications" value={a.length} icon={FileText} trend="Live database"/><KPICard title="Approved" value={approved} icon={CheckCircle} trend="Recorded decisions"/><KPICard title="Manual Review" value={manual} icon={AlertTriangle} trend="Needs attention"/></div><div className="glass-panel rounded-[2rem] p-6 lg:p-8"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-2xl font-semibold text-foreground">Recent Applications</h2><p className="mt-1 text-sm text-muted-foreground">No demo data — this table reads from RiskSure.</p></div><Link href="/new-application"><Button className="rounded-2xl"><Plus className="mr-2 h-4 w-4"/>New Application</Button></Link></div>{loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin"/></div>:error?<p className="rounded-2xl bg-destructive/10 p-4 text-destructive">{error}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-white/10 text-left text-muted-foreground"><th className="p-3">Name</th><th className="p-3">Risk</th><th className="p-3">Decision</th><th className="p-3 text-right">Premium</th></tr></thead><tbody>{a.map(x=><tr key={x.id} className="border-b border-white/5"><td className="p-3 font-medium">{x.name}</td><td className="p-3">{(x.risk_score*100).toFixed(0)}%</td><td className="p-3"><StatusBadge status={x.decision}/></td><td className="p-3 text-right">{x.premium>0?`$${x.premium.toLocaleString()}`:"-"}</td></tr>)}</tbody></table>{!a.length&&<p className="py-10 text-center text-muted-foreground">No applications yet.</p>}</div>}</div></div></DashboardLayout>}
